BEGIN;

DROP TABLE IF EXISTS check_results;

CREATE TABLE check_results (
    id BIGSERIAL PRIMARY KEY,
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    r DOUBLE PRECISION NOT NULL,
    hit BOOLEAN NOT NULL,
    check_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    execution_time BIGINT
);

COMMIT;
